import React, { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";

const TermsOfService = () => {
  useEffect(() => {
    AOS.init();
  });
  return (
    <>
      <div className="2xl:mx-auto pt-[40%] md:pt-[3%] 2xl:container xl:px-20 md:px-6 p-4 py-28 lg:flex items-stretch  justify-between">
        <div className="lg:w-2/4  pr-4">
          <div data-aos="fade-up" data-aos-once="false" className>
            <h1
              data-aos="fade-up"
              data-aos-once="false"
              data-aos-duration="2000"
              className="lg:text-5xl text-3xl font-bold text-gray-800"
            >
              Terms Of Service
            </h1>
            <p
              data-aos="fade-up"
              data-aos-once="false"
              data-aos-duration="2000"
              className="text-base leading-6 text-justify text-gray-600 mt-4"
            >
              We request our customers to thoroughly go through our terms of
              services and usage before signing up for our FTTH broadband plans.
              We reserve the right to modify, delete, update or add to any or
              all sections of this policy and our terms and conditions including
              terms of service anytime, with or without prior intimation.
              Customers are therefore requested to go through these from time to
              time.
            </p>
          </div>

          <ul className="mt-12 text-justify list-decimal ml-5">
            <li
              data-aos="fade-up"
              data-aos-once="false"
              data-aos-duration="2000"
              className="text-base leading-6 text-gray-600 mt-4"
            >
              We provide services in accordance with the registered plan on our
              website. Any interruptions in service are to be reported
              immediately by our customers to their service representatives for
              accelerated resolution.
            </li>
            <li
              data-aos="fade-up"
              data-aos-once="false"
              data-aos-duration="2000"
              className="text-base leading-6 text-gray-600 mt-4"
            >
              Broadband speeds and bandwidth will be based on the terms of the
              plan selected by you during the registration process, and in case
              you want to modify this, you are requested to get in touch with
              our service representatives
            </li>
            <li
              data-aos="fade-up"
              data-aos-once="false"
              data-aos-duration="2000"
              className="text-base leading-6 text-gray-600 mt-4"
            >
              Bills incurred by the use of our services will be generated by the
              15th of every month and invoiced to you. In case of any queries,
              you are requested to contact our customer service personnel
            </li>
            <li
              data-aos="fade-up"
              data-aos-once="false"
              data-aos-duration="2000"
              className="text-base leading-6 text-gray-600 mt-4"
            >
              Our ground staff will provide you technical services to the best
              of our abilities, but we are not deemed to be liable for failure
              to do so owing to reasons beyond our control.
            </li>
            <li
              data-aos="fade-up"
              data-aos-once="false"
              data-aos-duration="2000"
              className="text-base leading-6 text-gray-600 mt-4"
            >
              If for any reason, the ground inspection is not favorable for
              providing our services, we will provide you a full refund of the
              installation charges within 15 working days.
            </li>
            <li
              data-aos="fade-up"
              data-aos-once="false"
              data-aos-duration="2000"
              className="text-base leading-6 text-gray-600 mt-4"
            >
              Invoices will have to be paid on or before the due date and
              failure to do so would incur penal charges or late fee. We also
              reserve the right to discontinue the provision of our services if
              we deem it necessary.
            </li>
          </ul>
        </div>
        <div
          data-aos="zoom-in-down"
          data-aos-once="false"
          data-aos-duration="2000"
          className="xl:w-1/2  sm:w-8/12 relative lg:mt-0 mt-12 lg:flex hidden items-center lg:justify-end justify-center "
        >
          <img
            src="https://i.ibb.co/GcW89gm/img1.png"
            className="w-8/12 h-full object-cover object-center md:flex hidden"
            alt="group meeting"
          />
          <img
            src="https://i.ibb.co/ZYYffvx/img2.png"
            className="md:w-auto w-full md:absolute top-0 h-full py-8 left-0 md:ml-10 object-cover object-center"
            alt="lady working"
          />
        </div>
        <div className="lg:mt-0 mt-12 lg:hidden md:block hidden w-full">
          <img
            src="https://i.ibb.co/L9RDbBd/Group-811183.png"
            alt="lady workin"
            className="w-full"
          />
        </div>
        <div className="mt-12 md:hidden w-full">
          <img
            src="https://i.ibb.co/ZYYffvx/img2.png"
            alt="woman working"
            className="w-full"
          />
        </div>
      </div>
      <div className=" mx-[5%] pt-16">
        <div className="mb-12 ">
          <p
            data-aos="fade-down"
            data-aos-once="false"
            className="text-xl text-gray-600 text-justify"
          >
            Payments by way of cheques, pay orders, or demand drafts will have
            to be made at National Capital Region of Delhi made in favor of
            UltraNet Account Number – -xxxx in xxx bank. We do not accept any
            outstation cheques and any such cheques addressed to us will be
            returned to the customer’s registered address for communication. A
            charge of Rs.150 shall be levied for postage and communication along
            with late fee charges incurred, if any.
          </p>
        </div>
        <div
          data-aos="zoom-in-down"
          data-aos-once="false"
          data-aos-duration="2000"
          className="relative bg-center bg-cover bg-no-repeat mb-10  mx-auto  h-64"
        >
          <img
            src="https://tuk-cdn.s3.amazonaws.com/assets/components/blog/b_3_0.png"
            alt=""
            className="h-full w-full object-cover overflow-hidden absolute rounded"
          />
        </div>
        <div
          data-aos="zoom-in-down"
          data-aos-once="false"
          className="  mx-auto "
        >
          <p className="mb-4 font-bold text-gray-800 text-base">
            You can pay us by any of the following methods:
          </p>
          <ul
            data-aos="zoom-in-down"
            data-aos-once="false"
            data-aos-duration="2000"
            className="list-decimal ml-5"
          >
            <li>Credit cards</li>
            <li>Debit cards</li>
            <li>Standing instructions on your bank account</li>
            <li>Payment through cheque, demand draft or pay order</li>
            <li>Manual payment by cash at one of our branch offices</li>
            <li>Online payment through NEFT or IMPS clearance</li>
            <li>Through phone banking</li>
          </ul>
        </div>
      </div>
    </>
  );
};

export default TermsOfService;
